coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
ignore:
  - "app/functions.php"
