coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
